<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Controller\IndexController'           => __DIR__ . '/src/Application/Controller/IndexController.php',
    'ApplicationTest\Framework\TestCase'               => __DIR__ . '/tests/ApplicationTest/Framework/TestCase.php',
    'ApplicationTest\Framework\TestCaseOptions'        => __DIR__ . '/tests/ApplicationTest/Framework/TestCaseOptions.php',
    'ApplicationTest\Mapper\DoctrineORMMapperTestCase' => __DIR__ . '/tests/ApplicationTest/Framework/DoctrineORMMapperTestCase.php',
    'ApplicationTest\Mapper\DoctrineORMMapperTest'     => __DIR__ . '/tests/ApplicationTest/Mapper/DoctrineORMMapperTest.php',
    'Application\Module'                               => __DIR__ . '/Module.php',
);